### ISSUE TITLE
ImageArray is signed

### ISSUE THREAD

**Issue by pchev** [cedric-r/ASCOM.HomeMade.SBIGCamera#1] opened 2021-08-10 09:13 UTC
Hi Cedric,

I receive a message on CN from a CCDciel user that get an access violation exception when reading the imagearray using a ASCOM.HomeMade.SBIGCamera driver. A quick search about this driver take me here and I see you are the author of this :) congratulation to take this well needed task!

Not sure if this is related to this error but looking at the code I remark the imagearray is defined as unsigned when the ascom specification is 32bit signed integer.
Definition found at row 26 of ASCOM.HomeMade.SBIGCommon/ISBIGCamera.cs :
public UInt32[,] cameraImageArray;
must be:
public int[,] cameraImageArray;

Patrick

**Comment by cedric-r** [comment] 2021-08-11 14:57
Hi Patrick,

Yes, I needed one so wrote one. I'm still working on sharing the USB connection with several processes (e.g. NINA + phd).

The library made by DL uses usigned ints everywhere, that's where it comes from. But I'll convert them to signed ints.

Thanks.

**Comment by cedric-r** [comment] 2021-08-12 08:07
Fixed in 0.19.17.

**Comment by cedric-r** [comment] 2021-08-13 12:19
The problem is still here. I've tried debugging with CCDCiel, but apart from a crash, I don't get anywhere. The image buffer is now the right way (horizontal) and the numbers are signed ints. Any idea Patrick?

**Comment by pchev** [comment] 2021-08-13 14:15
It is difficult to get more information from the current version of CCDciel because I rely on FPC internal to map the SafeArray directly to a Pascal array. This is about the same magic that C# do to transform the integer array to a SafeArray object.

I make a change to a new branch "safearray" to get more detail on the process. 
Now in cu_ascomcamera at line 563 it simply get a variant for the ImageArray. 
Then in subsequent lines it get the array dimension and size.
A critical point is at line 616 where it get the pointer to the array data. The data itself is read at line 692.
For me this work the same with the camera simulator.

Can you try with this branch to see if this work or if this can give more information.

**Comment by cedric-r** [comment] 2021-08-13 14:22
Testing right now.

**Comment by cedric-r** [comment] 2021-08-13 14:27
It shows width amd height=0 and then crash when trying to access V.ElectronsPerADU.

2021-08-13T16:23:08.613  CCDciel Version beta 0.9.75-Unknown-revision 2021/08/13 16:22:46
2021-08-13T16:23:08.613  Compiled with: Lazarus 2.0.0.1 Free Pascal 3.0.4 Win32-i386-win32
2021-08-13T16:23:08.641 9: Using a maximum of 8 parallel processor
2021-08-13T16:23:09.330 9: Microsoft Windows 10 Professionnel 10.0.19043 64-bit
2021-08-13T16:23:11.144 9: ASCOM Platform 6.5, 6.5.1.3234
2021-08-13T16:23:11.145 1: CCDciel Version beta 0.9.75 Copyright (C) 2021 Patrick Chevalley. This is free software, you can redistribute it under certain conditions.
2021-08-13T16:23:11.145 1: This program comes with ABSOLUTELY NO WARRANTY; for details see Help/About
2021-08-13T16:23:11.146 3: Using configuration file C:\Users\cedric\AppData\Local\ccdciel\ccdciel.conf
2021-08-13T16:23:11.896 1: TCP/IP server listen on port: 3277
2021-08-13T16:23:14.520 2: Connecting Camera ASCOM "ASCOM.HomeMade.SBIGImagingCamera" ...
2021-08-13T16:23:18.058 9: ASCOM.HomeMade.SBIGImagingCamera: Version: 0.20.22
2021-08-13T16:23:18.058 9: ASCOM.HomeMade.SBIGImagingCamera: Driver version: 0.20.22
2021-08-13T16:23:18.059 9: ASCOM.HomeMade.SBIGImagingCamera: Interface version: 3
2021-08-13T16:23:22.444 1: Camera connected
2021-08-13T16:23:23.457 3: ASCOM.HomeMade.SBIGImagingCamera: Connected
2021-08-13T16:23:23.460 2: Connecting Filter wheel ASCOM "ASCOM.HomeMade.SBIGFW" ...
2021-08-13T16:23:24.153 9: ASCOM.HomeMade.SBIGFW: Version: 0.20.22
2021-08-13T16:23:24.153 9: ASCOM.HomeMade.SBIGFW: Driver version: 0.20
2021-08-13T16:23:24.153 9: ASCOM.HomeMade.SBIGFW: Interface version: 2
2021-08-13T16:23:24.156 3: ASCOM.HomeMade.SBIGFW: Connected
2021-08-13T16:23:24.158 1: Filter wheel connected
2021-08-13T16:23:31.444 2: Start capture
2021-08-13T16:23:31.450 1: Starting Light exposure 1/1 for 1 seconds
2021-08-13T16:24:03.277 3: ASCOM.HomeMade.SBIGImagingCamera: read image.
2021-08-13T16:24:18.364 3: ASCOM.HomeMade.SBIGImagingCamera: width:0 height:0

I'm sure I've done something wrong in the driver and Nina/SGP/Voyager deal with it ok, but I can't think what.

**Comment by cedric-r** [comment] 2021-08-13 14:43
I have an idea. Testing something.

**Comment by pchev** [comment] 2021-08-13 14:43
The size of 0 is probably why it crash with the standard FPC method.

ElectronsPerADU is not a problem, it is within try...except , and must continue.
But probably the next row pimgdata:=VarArrayLock(imgvar); trow an "Invalid variant ..." exception.

I will try to make more comparison between your driver and the simulator to this int array to safearray magic work.

**Comment by pchev** [comment] 2021-08-13 14:55
Do you already try with the ASCOM Conformance tool?  https://ascom-standards.org/Developer/Conformance.htm
Maybe it can give useful hint.

**Comment by cedric-r** [comment] 2021-08-13 15:06
I haven't. I'll have a look. 

I tried to change the type of the image array to Array instead of the .net default type, but it didn't make any difference with CCDCiel. I suspect NINA and SGP are ,net-based, so the type of the array deosn't matter much. CCDCiel being Pascal, the types are incompatible. But I thought Array would be what's needed since it's supposed to describe the array as expected by CCDCiel. But the dimension is still 0,0.

But I think that's where the problem is, so I'll look into it.

**Comment by pchev** [comment] 2021-08-14 08:28
I make a minor change to CCDciel safearray branch to use directly the functions in oleaut32.dll without any FPC wrapper. 
This is controlled by {$define DirectOleaut32}, active by default.

For example to get the array size it call directly SafeArrayGetUBound https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-safearraygetubound

**Comment by pchev** [comment] 2021-08-14 08:53
Continuing to compare your code with the simulator...

Simulator:
    [Guid("12229c31-e7d6-49e8-9c5d-5d7ff05c3bfe"), ClassInterface(ClassInterfaceType.None), ComVisible(true)]
    public class Camera : ICameraV3
    
SBIG:
    [Guid("3a7e63ad-c913-44f0-9489-e1744c9c2991")]
    [ClassInterface(ClassInterfaceType.None)]
    [ProgId(Camera.driverID)]
    public class Camera : ISBIGCamera, ICameraV3, ICameraV2

Is the ComVisible(true) attribute related to how the ImageArray is mapped to Com compatible array?

**Comment by cedric-r** [comment] 2021-08-16 14:46
Patrick,

Thanks for mentioning the ASCOM local server. I didn't know about it. I rewrote the whole driver this weekend to port it to that. I haven't had time to test with CCDCiel yet.

On a side note, it passed ASCOM certification, including the image array:
 
ConformanceCheck ASCOM Device Conformance Checker Version 6.5.7831.20978, Build time: 10/06/2021 11:39:22
ConformanceCheck Running on: ASCOM Platform 6.5 SP1 6.5.1.3234
 
ConformanceCheck Driver ProgID: ASCOM.HomeMade.SBIGImagingCamera
 
Error handling 
Error number for "Not Implemented" is: 80040400
Error number for "Invalid Value 1" is: 80040405
Error number for "Value Not Set 1" is: 80040402
Error number for "Value Not Set 2" is: 80040403
Error messages will not be interpreted to infer state.
 
16:41:20.406 Driver Access Checks              OK       
16:41:21.243 AccessChecks                      OK       Successfully created driver using late binding
16:41:22.133 AccessChecks                      OK       Successfully connected using late binding
16:41:22.137 AccessChecks                      INFO     The driver is a COM object
16:41:22.818 AccessChecks                      INFO     Driver does not expose interface ICamera
16:41:22.902 AccessChecks                      INFO     Device exposes interface ICameraV2
16:41:22.932 AccessChecks                      OK       Successfully created driver using driver access toolkit
16:41:22.957 AccessChecks                      OK       Successfully connected using driver access toolkit
 
Conform is using ASCOM.DriverAccess.Camera to get a Camera object
16:41:22.976 ConformanceCheck                  OK       Driver instance created successfully
16:41:23.055 ConformanceCheck                  OK       Connected OK
 
Common Driver Methods 
16:41:23.103 InterfaceVersion                  OK       3
16:41:23.140 Connected                         OK       True
16:41:23.187 Description                       OK       ASCOM SBIG Imaging Camera Driver.
16:41:23.236 DriverInfo                        OK       Version: 0.21.36
16:41:23.281 DriverVersion                     OK       0.21.36
16:41:23.325 Name                              OK       ASCOM driver for SBIG cameras
16:41:23.373 CommandString                     INFO     Conform cannot test the CommandString method
16:41:23.381 CommandBlind                      INFO     Conform cannot test the CommandBlind method
16:41:23.392 CommandBool                       INFO     Conform cannot test the CommandBool method
16:41:23.402 Action                            INFO     Conform cannot test the Action method
16:41:23.420 SupportedActions                  OK       Driver returned an empty action list
 
Can Properties 
16:41:23.505 CanAbortExposure                  OK       True
16:41:23.514 CanAsymmetricBin                  OK       False
16:41:23.523 CanGetCoolerPower                 OK       True
16:41:23.534 CanPulseGuide                     OK       False
16:41:23.541 CanSetCCDTemperature              OK       True
16:41:23.548 CanStopExposure                   OK       True
16:41:23.555 CanFastReadout                    OK       True
 
Pre-run Checks 
 
Last Tests 
16:41:23.706 LastExposureDuration              OK       LastExposureDuration correctly generated a COM exception before an exposure was made
16:41:23.716 LastExposureStartTime             OK       LastExposureStartTime correctly generated a COM exception before an exposure was made
 
Properties 
16:41:23.788 MaxBinX                           OK       3
16:41:23.841 MaxBinY                           OK       3
16:41:23.907 BinX Read                         OK       1
16:41:23.965 BinY Read                         OK       1
16:41:24.013 BinX Write                        OK       Exception correctly generated on setting BinX to 0
16:41:24.025 BinX Write                        OK       Exception correctly generated on setting BinX to 4
16:41:24.037 BinY Write                        OK       Exception correctly generated on setting BinY to 0
16:41:24.047 BinY Write                        OK       Exception correctly generated on setting BinY to 4
16:41:24.055 BinXY Write                       OK       Successfully set symmetric xy binning: 1 x 1
16:41:24.063 BinXY Write                       OK       Successfully set symmetric xy binning: 2 x 2
16:41:24.070 BinXY Write                       OK       Successfully set symmetric xy binning: 3 x 3
16:41:24.078 CameraState                       OK       cameraIdle
16:41:24.119 CameraXSize                       OK       3358
16:41:24.166 CameraYSize                       OK       2536
16:41:24.217 CCDTemperature                    OK       27.28125
16:41:24.261 CoolerOn Read                     OK       False
16:41:24.308 CoolerOn Write                    OK       Successfully changed CoolerOn state
16:41:24.330 CoolerPower                       OK       0
16:41:24.392 ElectronsPerADU                   OK       Optional member threw a PropertyNotImplementedException exception.
16:41:24.447 FullWellCapacity                  OK       Optional member threw a PropertyNotImplementedException exception.
16:41:24.493 HasShutter                        OK       True
16:41:24.540 HeatSinkTemperature               OK       0
16:41:24.587 ImageReady                        OK       False
16:41:24.634 ImageArray                        OK       Exception correctly generated when ImageReady is false
16:41:24.646 ImageArrayVariant                 OK       Exception correctly generated when ImageReady is false
16:41:24.658 IsPulseGuiding                    OK       Optional member threw a PropertyNotImplementedException exception.
16:41:24.694 MaxADU                            OK       50000
16:41:24.741 NumX Read                         OK       3358
16:41:24.789 NumX write                        OK       Successfully wrote 1679
16:41:24.799 NumY Read                         OK       2536
16:41:24.836 NumY write                        OK       Successfully wrote 1268
16:41:24.846 PixelSizeX                        OK       5.4
16:41:24.898 PixelSizeY                        OK       5.4
16:41:24.944 SetCCDTemperature Read            OK       0
16:41:24.989 SetCCDTemperature Write           OK       Successfully wrote 0.0
16:41:25.006 SetCCDTemperature Write           INFO     Setpoint lower limit found in the range -100.000 to -104.999 degrees
16:41:25.022 SetCCDTemperature Write           INFO     Setpoint can be set to 100.000 degrees
16:41:25.031 StartX Read                       OK       0
16:41:25.082 StartX write                      OK       Successfully wrote 1679
16:41:25.092 StartY Read                       OK       0
16:41:25.144 StartY write                      OK       Successfully wrote 1268
16:41:25.155 SensorType Read                   OK       Monochrome
16:41:25.169 BayerOffsetX Read                 OK       Sensor type is Monochrome and a PropertyNotImplementedException exception was generated as expected
16:41:25.182 BayerOffsetY Read                 OK       Sensor type is Monochrome and a PropertyNotImplementedException exception was generated as expected
16:41:25.194 ExposureMax Read                  OK       167777.16
16:41:25.208 ExposureMin Read                  OK       0
16:41:25.219 ExposureMin                       OK       ExposureMin is less than or equal to ExposureMax
16:41:25.231 ExposureResolution Read           OK       0
16:41:25.243 ExposureResolution                OK       ExposureResolution is less than or equal to ExposureMax
16:41:25.256 FastReadout Read                  OK       False
16:41:25.269 FastReadout Write                 OK       Able to change the FastReadout state OK
16:41:25.284 GainMin Read                      OK       Optional member threw a PropertyNotImplementedException exception.
16:41:25.298 GainMax Read                      OK       Optional member threw a PropertyNotImplementedException exception.
16:41:25.312 Gains Read                        OK       Optional member threw a PropertyNotImplementedException exception.
16:41:25.327 Gain Read                         OK       Optional member threw a PropertyNotImplementedException exception.
16:41:25.340 Gain Read                         OK       All four gain properties throw exceptions - the driver is in "Gain Not Implemented" mode.
16:41:25.355 Gain Write                        OK       PropertyNotImplementedException is expected and a PropertyNotImplementedException exception was generated as expected
16:41:25.369 PercentCompleted Read             OK       Optional member threw a PropertyNotImplementedException exception.
16:41:25.380 ReadoutModes Read                 OK       RM_1X1
16:41:25.392 ReadoutModes Read                 OK       RM_2X2
16:41:25.404 ReadoutModes Read                 OK       RM_3X3
16:41:25.414 ReadoutModes Read                 OK       RM_NX1
16:41:25.425 ReadoutModes Read                 OK       RM_NX2
16:41:25.435 ReadoutModes Read                 OK       RM_NX3
16:41:25.446 ReadoutModes Read                 OK       RM_1X1_VOFFCHIP
16:41:25.458 ReadoutModes Read                 OK       RM_2X2_VOFFCHIP
16:41:25.468 ReadoutModes Read                 OK       RM_3X3_VOFFCHIP
16:41:25.478 ReadoutModes Read                 OK       RM_9X9
16:41:25.490 ReadoutModes Read                 OK       RM_NXN
16:41:25.503 ReadoutMode Read                  OK       0
16:41:25.513 ReadoutMode Index                 OK       ReadReadoutMode is within the bounds of the ReadoutModes ArrayList
16:41:25.525 ReadoutMode Index                 INFO     Current value: RM_1X1
16:41:25.541 SensorName Read                   OK       SBIG STT-8300 3 CCD Camera
16:41:25.554 OffsetMin Read                    OK       Optional member threw a PropertyNotImplementedException exception.
16:41:25.569 OffsetMax Read                    OK       Optional member threw a PropertyNotImplementedException exception.
16:41:25.585 Offsets Read                      OK       Optional member threw a PropertyNotImplementedException exception.
16:41:25.595 Offset Read                       OK       Optional member threw a PropertyNotImplementedException exception.
16:41:25.607 Offset Read                       OK       All four offset properties throw exceptions - the driver is in "Offset Not Implemented" mode.
16:41:25.620 Offset Write                      OK       PropertyNotImplementedException is expected and a PropertyNotImplementedException exception was generated as expected
16:41:25.631 SubExposureDuration               OK       Optional member threw a PropertyNotImplementedException exception.
16:41:25.673 SubExposureDuration write         OK       Optional member threw a PropertyNotImplementedException exception.
 
Methods 
16:41:25.750 AbortExposure                     OK       No exception generated when camera is already idle
16:41:25.762 PulseGuide                        OK       CanPulseGuide is false and PulseGuide is not implemented in this driver
16:41:25.776 StopExposure                      OK       No exception generated when camera is already idle
 
Take image full frame 1 x 1 bin 
16:41:29.918 StartExposure                     OK       Asynchronous exposure found OK: 2 seconds
16:41:29.955 LastExposureDuration              OK       LastExposureDuration is: 2 seconds
16:41:29.991 LastExposureStartTime             OK       LastExposureStartTime is correct to within 2 seconds: 2021-08-16T16:41:25 UTC
16:41:30.241 ImageArray                        OK       Successfully read 32 bit integer array (1 plane) 3358 x 2536 pixels
16:41:36.017 ImageArrayVariant                 OK       Successfully read variant array (1 plane) with System.Int32 elements 3358 x 2536 pixels
 
Take image full frame 2 x 2 bin 
16:41:39.452 StartExposure                     OK       Asynchronous exposure found OK: 2 seconds
16:41:39.464 LastExposureDuration              OK       LastExposureDuration is: 2 seconds
16:41:39.479 LastExposureStartTime             OK       LastExposureStartTime is correct to within 2 seconds: 2021-08-16T16:41:36 UTC
16:41:39.535 ImageArray                        OK       Successfully read 32 bit integer array (1 plane) 1679 x 1268 pixels
16:41:40.836 ImageArrayVariant                 OK       Successfully read variant array (1 plane) with System.Int32 elements 1679 x 1268 pixels
 
Take image full frame 3 x 3 bin 
16:41:43.684 StartExposure                     OK       Asynchronous exposure found OK: 2 seconds
16:41:43.714 LastExposureDuration              OK       LastExposureDuration is: 2 seconds
16:41:43.738 LastExposureStartTime             OK       LastExposureStartTime is correct to within 2 seconds: 2021-08-16T16:41:40 UTC
16:41:43.774 ImageArray                        OK       Successfully read 32 bit integer array (1 plane) 1119 x 845 pixels
16:41:44.311 ImageArrayVariant                 OK       Successfully read variant array (1 plane) with System.Int32 elements 1119 x 845 pixels
 
StartExposure error cases 
16:41:44.398 StartExposure                     OK       Exception correctly generated for negative duration
16:41:44.461 StartExposure                     OK       Exception correctly generated for X size larger than binned chip size, Bin 1x1
16:41:44.520 StartExposure                     OK       Exception correctly generated for Y size larger than binned chip size, Bin 1x1
16:41:44.582 StartExposure                     OK       Exception correctly generated for X start outside binned chip size, Bin 1x1
16:41:44.641 StartExposure                     OK       Exception correctly generated for Y start outside binned chip size, Bin 1x1
16:41:44.701 StartExposure                     OK       Exception correctly generated for X size larger than binned chip size, Bin 2x2
16:41:44.748 StartExposure                     OK       Exception correctly generated for Y size larger than binned chip size, Bin 2x2
16:41:44.794 StartExposure                     OK       Exception correctly generated for X start outside binned chip size, Bin 2x2
16:41:44.840 StartExposure                     OK       Exception correctly generated for Y start outside binned chip size, Bin 2x2
16:41:44.886 StartExposure                     OK       Exception correctly generated for X size larger than binned chip size, Bin 3x3
16:41:44.932 StartExposure                     OK       Exception correctly generated for Y size larger than binned chip size, Bin 3x3
16:41:44.978 StartExposure                     OK       Exception correctly generated for X start outside binned chip size, Bin 3x3
16:41:45.023 StartExposure                     OK       Exception correctly generated for Y start outside binned chip size, Bin 3x3
 
Post-run Checks 
16:41:45.177 PostRunCheck                      OK       Camera returned to initial cooler temperature
 
Conformance test complete 
 
No errors, warnings or issues found: your driver passes ASCOM validation!!

**Comment by pchev** [comment] 2021-08-16 18:08
This is excellent! congratulation!

If CCDciel still not work, can you try with PHD2. This is a C++ application and it use the same SafeArray functions to get the image.

**Comment by cedric-r** [comment] 2021-08-16 18:28
Phd definitively works I just it to test access to the guiding sensor.

I'll test with ccdciel tomorrow. One of my testers told me tonight that today's version works with ccdciel. I'll confirm asap.

**Comment by cedric-r** [comment] 2021-08-17 10:34
Patrick, I tested with the latest version of CCDCiel (the one you modified) and it's working fine:

12:32:19 CCDciel Version beta 0.9.75 Copyright (C) 2021 Patrick Chevalley. This is free software, you can redistribute it under certain conditions.
12:32:19 This program comes with ABSOLUTELY NO WARRANTY; for details see Help/About
12:32:19 Using configuration file C:\Users\cedric\AppData\Local\ccdciel\ccdciel.conf
12:32:20 TCP/IP server listen on port: 3277
12:32:23 Connecting Camera ASCOM "ASCOM.HomeMade.SBIGImagingCamera" ...
12:32:24 Camera connected
12:32:25 ASCOM.HomeMade.SBIGImagingCamera: Connected
12:32:25 Connecting Filter wheel ASCOM "ASCOM.HomeMade.SBIGFW" ...
12:32:25 ASCOM.HomeMade.SBIGFW: Connected
12:32:25 Filter wheel connected
12:32:27 Camera frame x=0 y=0 width=3358 height=2536
12:32:31 Start capture
12:32:31 Starting Light exposure 1/1 for 1 seconds
12:32:36 ASCOM.HomeMade.SBIGImagingCamera: read image.
12:32:39 ASCOM.HomeMade.SBIGImagingCamera: width:3358 height:2536
12:32:39 ASCOM.HomeMade.SBIGImagingCamera: write image
12:32:39 ASCOM.HomeMade.SBIGImagingCamera: release imagearray
12:32:41 ASCOM.HomeMade.SBIGImagingCamera: Error: Unknown telescope focal length, set in telescope driver or in PREFERENCE, ASTROMETRY.
12:32:41 Saved file C:\Users\cedric\OneDrive\Documents\Documents\_Filter-1_20210817_103241.fits
12:32:41 Stop capture, Capture 1/1 Finished
12:32:46 Start capture
12:32:46 Starting Light exposure 1/1 for 1 seconds
12:32:50 ASCOM.HomeMade.SBIGImagingCamera: read image.
12:33:11 ASCOM.HomeMade.SBIGImagingCamera: width:3358 height:2536
12:33:11 ASCOM.HomeMade.SBIGImagingCamera: write image
12:33:11 ASCOM.HomeMade.SBIGImagingCamera: release imagearray
12:33:13 ASCOM.HomeMade.SBIGImagingCamera: Error: Unknown telescope focal length, set in telescope driver or in PREFERENCE, ASTROMETRY.
12:33:14 Saved file C:\Users\cedric\OneDrive\Documents\Documents\_Filter-1_20210817_103313.fits
12:33:14 Stop capture, Capture 1/1 Finished
12:33:21 Start capture
12:33:21 Set Binning 2x2
12:33:21 ASCOM.HomeMade.SBIGImagingCamera: Set binning 2x2
12:33:22 Camera frame x=0 y=0 width=1679 height=1268
12:33:23 Starting Light exposure 1/1 for 1 seconds
12:33:28 ASCOM.HomeMade.SBIGImagingCamera: read image.
12:33:28 ASCOM.HomeMade.SBIGImagingCamera: width:1679 height:1268
12:33:28 ASCOM.HomeMade.SBIGImagingCamera: write image
12:33:28 ASCOM.HomeMade.SBIGImagingCamera: release imagearray
12:33:28 ASCOM.HomeMade.SBIGImagingCamera: Error: Unknown telescope focal length, set in telescope driver or in PREFERENCE, ASTROMETRY.
12:33:28 Saved file C:\Users\cedric\OneDrive\Documents\Documents\_Filter-1_20210817_103328.fits
12:33:28 Stop capture, Capture 1/1 Finished
12:33:33 Start capture
12:33:33 Set Binning 3x3
12:33:33 ASCOM.HomeMade.SBIGImagingCamera: Set binning 3x3
12:33:34 Camera frame x=0 y=0 width=1119 height=845
12:33:35 Starting Light exposure 1/1 for 1 seconds
12:33:37 ASCOM.HomeMade.SBIGImagingCamera: read image.
12:33:37 ASCOM.HomeMade.SBIGImagingCamera: width:1119 height:845
12:33:37 ASCOM.HomeMade.SBIGImagingCamera: write image
12:33:37 ASCOM.HomeMade.SBIGImagingCamera: release imagearray
12:33:37 ASCOM.HomeMade.SBIGImagingCamera: Error: Unknown telescope focal length, set in telescope driver or in PREFERENCE, ASTROMETRY.
12:33:37 Saved file C:\Users\cedric\OneDrive\Documents\Documents\_Filter-1_20210817_103337.fits
12:33:37 Stop capture, Capture 1/1 Finished
12:33:40 Start capture
12:33:40 Starting Light exposure 1/1 for 1 seconds
12:33:42 ASCOM.HomeMade.SBIGImagingCamera: read image.
12:33:42 ASCOM.HomeMade.SBIGImagingCamera: width:1119 height:845
12:33:42 ASCOM.HomeMade.SBIGImagingCamera: write image
12:33:43 ASCOM.HomeMade.SBIGImagingCamera: release imagearray
12:33:43 ASCOM.HomeMade.SBIGImagingCamera: Error: Unknown telescope focal length, set in telescope driver or in PREFERENCE, ASTROMETRY.
12:33:43 Saved file C:\Users\cedric\OneDrive\Documents\Documents\_Filter-1_20210817_103343.fits
12:33:43 Stop capture, Capture 1/1 Finished
12:33:48 Start capture
12:33:48 Starting Light exposure 1/1 for 1 seconds
12:33:50 ASCOM.HomeMade.SBIGImagingCamera: read image.
12:33:50 ASCOM.HomeMade.SBIGImagingCamera: width:1119 height:845
12:33:50 ASCOM.HomeMade.SBIGImagingCamera: write image
12:33:50 ASCOM.HomeMade.SBIGImagingCamera: release imagearray
12:33:50 ASCOM.HomeMade.SBIGImagingCamera: Error: Unknown telescope focal length, set in telescope driver or in PREFERENCE, ASTROMETRY.
12:33:50 Saved file C:\Users\cedric\OneDrive\Documents\Documents\_Filter-1_20210817_103350.fits
12:33:50 Stop capture, Capture 1/1 Finished
12:33:54 Start capture
12:33:54 Set Binning 1x1
12:33:54 ASCOM.HomeMade.SBIGImagingCamera: Set binning 1x1
12:33:55 Camera frame x=0 y=0 width=3358 height=2536
12:33:56 Starting Light exposure 1/1 for 1 seconds
12:33:59 ASCOM.HomeMade.SBIGImagingCamera: read image.
12:33:59 ASCOM.HomeMade.SBIGImagingCamera: width:3358 height:2536
12:33:59 ASCOM.HomeMade.SBIGImagingCamera: write image
12:33:59 ASCOM.HomeMade.SBIGImagingCamera: release imagearray
12:33:59 ASCOM.HomeMade.SBIGImagingCamera: Error: Unknown telescope focal length, set in telescope driver or in PREFERENCE, ASTROMETRY.
12:33:59 Saved file C:\Users\cedric\OneDrive\Documents\Documents\_Filter-1_20210817_103359.fits
12:34:00 Stop capture, Capture 1/1 Finished

**Closed as completed by cedric-r** 2021-08-17 10:34 UTC

**Comment by cedric-r** [comment] 2021-08-17 10:37
I've also tested with standard 0.9.75 and everything is good.

**Comment by pchev** [comment] 2021-08-17 11:26
Thank you Cedric!
